"""Initial KSP schema

Revision ID: 554d1c23fc96
Revises: 
Create Date: 2026-07-24 20:41:31.046706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554d1c23fc96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('act',
    sa.Column('ActCode', sa.String(), nullable=False),
    sa.Column('ActDescription', sa.String(), nullable=True),
    sa.Column('ShortName', sa.String(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ActCode')
    )
    op.create_table('casecategory',
    sa.Column('CaseCategoryID', sa.Integer(), nullable=False),
    sa.Column('LookupValue', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CaseCategoryID')
    )
    op.create_table('casestatusmaster',
    sa.Column('CaseStatusID', sa.Integer(), nullable=False),
    sa.Column('CaseStatusName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CaseStatusID')
    )
    op.create_table('castemaster',
    sa.Column('caste_master_id', sa.Integer(), nullable=False),
    sa.Column('caste_master_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('caste_master_id')
    )
    op.create_table('crimehead',
    sa.Column('CrimeHeadID', sa.Integer(), nullable=False),
    sa.Column('CrimeGroupName', sa.String(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('CrimeHeadID')
    )
    op.create_table('designation',
    sa.Column('DesignationID', sa.Integer(), nullable=False),
    sa.Column('DesignationName', sa.String(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.Column('SortOrder', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('DesignationID')
    )
    op.create_table('gravityoffence',
    sa.Column('GravityOffenceID', sa.Integer(), nullable=False),
    sa.Column('LookupValue', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('GravityOffenceID')
    )
    op.create_table('occupationmaster',
    sa.Column('OccupationID', sa.Integer(), nullable=False),
    sa.Column('OccupationName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('OccupationID')
    )
    op.create_table('rank',
    sa.Column('RankID', sa.Integer(), nullable=False),
    sa.Column('RankName', sa.String(), nullable=True),
    sa.Column('Hierarchy', sa.Integer(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('RankID')
    )
    op.create_table('religionmaster',
    sa.Column('ReligionID', sa.Integer(), nullable=False),
    sa.Column('ReligionName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ReligionID')
    )
    op.create_table('state',
    sa.Column('StateID', sa.Integer(), nullable=False),
    sa.Column('StateName', sa.String(), nullable=True),
    sa.Column('NationalityID', sa.Integer(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('StateID')
    )
    op.create_table('unittype',
    sa.Column('UnitTypeID', sa.Integer(), nullable=False),
    sa.Column('UnitTypeName', sa.String(), nullable=True),
    sa.Column('CityDistState', sa.String(), nullable=True),
    sa.Column('Hierarchy', sa.Integer(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('UnitTypeID')
    )
    op.create_table('crimesubhead',
    sa.Column('CrimeSubHeadID', sa.Integer(), nullable=False),
    sa.Column('CrimeHeadID', sa.Integer(), nullable=True),
    sa.Column('CrimeHeadName', sa.String(), nullable=True),
    sa.Column('SeqID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CrimeHeadID'], ['crimehead.CrimeHeadID'], ),
    sa.PrimaryKeyConstraint('CrimeSubHeadID')
    )
    op.create_table('district',
    sa.Column('DistrictID', sa.Integer(), nullable=False),
    sa.Column('DistrictName', sa.String(), nullable=True),
    sa.Column('StateID', sa.Integer(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['StateID'], ['state.StateID'], ),
    sa.PrimaryKeyConstraint('DistrictID')
    )
    op.create_table('section',
    sa.Column('SectionCode', sa.String(), nullable=False),
    sa.Column('ActCode', sa.String(), nullable=False),
    sa.Column('SectionDescription', sa.String(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ActCode'], ['act.ActCode'], ),
    sa.PrimaryKeyConstraint('SectionCode', 'ActCode')
    )
    op.create_table('court',
    sa.Column('CourtID', sa.Integer(), nullable=False),
    sa.Column('CourtName', sa.String(), nullable=True),
    sa.Column('DistrictID', sa.Integer(), nullable=True),
    sa.Column('StateID', sa.Integer(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['DistrictID'], ['district.DistrictID'], ),
    sa.ForeignKeyConstraint(['StateID'], ['state.StateID'], ),
    sa.PrimaryKeyConstraint('CourtID')
    )
    op.create_table('crimeheadactsection',
    sa.Column('CrimeHeadID', sa.Integer(), nullable=False),
    sa.Column('ActCode', sa.String(), nullable=False),
    sa.Column('SectionCode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ActCode', 'SectionCode'], ['section.ActCode', 'section.SectionCode'], ),
    sa.ForeignKeyConstraint(['CrimeHeadID'], ['crimehead.CrimeHeadID'], ),
    sa.PrimaryKeyConstraint('CrimeHeadID', 'ActCode', 'SectionCode')
    )
    op.create_table('unit',
    sa.Column('UnitID', sa.Integer(), nullable=False),
    sa.Column('UnitName', sa.String(), nullable=True),
    sa.Column('TypeID', sa.Integer(), nullable=True),
    sa.Column('ParentUnit', sa.Integer(), nullable=True),
    sa.Column('NationalityID', sa.Integer(), nullable=True),
    sa.Column('StateID', sa.Integer(), nullable=True),
    sa.Column('DistrictID', sa.Integer(), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['DistrictID'], ['district.DistrictID'], ),
    sa.ForeignKeyConstraint(['StateID'], ['state.StateID'], ),
    sa.ForeignKeyConstraint(['TypeID'], ['unittype.UnitTypeID'], ),
    sa.PrimaryKeyConstraint('UnitID')
    )
    op.create_table('employee',
    sa.Column('EmployeeID', sa.Integer(), nullable=False),
    sa.Column('DistrictID', sa.Integer(), nullable=True),
    sa.Column('UnitID', sa.Integer(), nullable=True),
    sa.Column('RankID', sa.Integer(), nullable=True),
    sa.Column('DesignationID', sa.Integer(), nullable=True),
    sa.Column('KGID', sa.String(), nullable=True),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('EmployeeDOB', sa.Date(), nullable=True),
    sa.Column('GenderID', sa.Integer(), nullable=True),
    sa.Column('BloodGroupID', sa.Integer(), nullable=True),
    sa.Column('PhysicallyChallenged', sa.Boolean(), nullable=True),
    sa.Column('AppointmentDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['DesignationID'], ['designation.DesignationID'], ),
    sa.ForeignKeyConstraint(['DistrictID'], ['district.DistrictID'], ),
    sa.ForeignKeyConstraint(['RankID'], ['rank.RankID'], ),
    sa.ForeignKeyConstraint(['UnitID'], ['unit.UnitID'], ),
    sa.PrimaryKeyConstraint('EmployeeID')
    )
    op.create_table('casemaster',
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('CrimeNo', sa.String(), nullable=True),
    sa.Column('CaseNo', sa.String(), nullable=True),
    sa.Column('CrimeRegisteredDate', sa.Date(), nullable=True),
    sa.Column('IncidentFromDate', sa.DateTime(), nullable=True),
    sa.Column('IncidentToDate', sa.DateTime(), nullable=True),
    sa.Column('InfoReceivedPSDate', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('BriefFacts', sa.Text(), nullable=True),
    sa.Column('PolicePersonID', sa.Integer(), nullable=True),
    sa.Column('PoliceStationID', sa.Integer(), nullable=True),
    sa.Column('CaseCategoryID', sa.Integer(), nullable=True),
    sa.Column('GravityOffenceID', sa.Integer(), nullable=True),
    sa.Column('CrimeMajorHeadID', sa.Integer(), nullable=True),
    sa.Column('CrimeMinorHeadID', sa.Integer(), nullable=True),
    sa.Column('CaseStatusID', sa.Integer(), nullable=True),
    sa.Column('CourtID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CaseCategoryID'], ['casecategory.CaseCategoryID'], ),
    sa.ForeignKeyConstraint(['CaseStatusID'], ['casestatusmaster.CaseStatusID'], ),
    sa.ForeignKeyConstraint(['CourtID'], ['court.CourtID'], ),
    sa.ForeignKeyConstraint(['CrimeMajorHeadID'], ['crimehead.CrimeHeadID'], ),
    sa.ForeignKeyConstraint(['CrimeMinorHeadID'], ['crimesubhead.CrimeSubHeadID'], ),
    sa.ForeignKeyConstraint(['GravityOffenceID'], ['gravityoffence.GravityOffenceID'], ),
    sa.ForeignKeyConstraint(['PolicePersonID'], ['employee.EmployeeID'], ),
    sa.ForeignKeyConstraint(['PoliceStationID'], ['unit.UnitID'], ),
    sa.PrimaryKeyConstraint('CaseMasterID')
    )
    op.create_table('accused',
    sa.Column('AccusedMasterID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=True),
    sa.Column('AccusedName', sa.String(), nullable=True),
    sa.Column('AgeYear', sa.Integer(), nullable=True),
    sa.Column('GenderID', sa.Integer(), nullable=True),
    sa.Column('PersonID', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['casemaster.CaseMasterID'], ),
    sa.PrimaryKeyConstraint('AccusedMasterID')
    )
    op.create_table('actsectionassociation',
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('ActID', sa.String(), nullable=False),
    sa.Column('SectionID', sa.String(), nullable=False),
    sa.Column('ActOrderID', sa.Integer(), nullable=True),
    sa.Column('SectionOrderID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ActID', 'SectionID'], ['section.ActCode', 'section.SectionCode'], ),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['casemaster.CaseMasterID'], ),
    sa.PrimaryKeyConstraint('CaseMasterID', 'ActID', 'SectionID')
    )
    op.create_table('chargesheetdetails',
    sa.Column('CSID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=True),
    sa.Column('csdate', sa.DateTime(), nullable=True),
    sa.Column('cstype', sa.CHAR(length=1), nullable=True),
    sa.Column('PolicePersonID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['casemaster.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['PolicePersonID'], ['employee.EmployeeID'], ),
    sa.PrimaryKeyConstraint('CSID')
    )
    op.create_table('complainantdetails',
    sa.Column('ComplainantID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=True),
    sa.Column('ComplainantName', sa.String(), nullable=True),
    sa.Column('AgeYear', sa.Integer(), nullable=True),
    sa.Column('OccupationID', sa.Integer(), nullable=True),
    sa.Column('ReligionID', sa.Integer(), nullable=True),
    sa.Column('CasteID', sa.Integer(), nullable=True),
    sa.Column('GenderID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['casemaster.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['CasteID'], ['castemaster.caste_master_id'], ),
    sa.ForeignKeyConstraint(['OccupationID'], ['occupationmaster.OccupationID'], ),
    sa.ForeignKeyConstraint(['ReligionID'], ['religionmaster.ReligionID'], ),
    sa.PrimaryKeyConstraint('ComplainantID')
    )
    op.create_table('victim',
    sa.Column('VictimMasterID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=True),
    sa.Column('VictimName', sa.String(), nullable=True),
    sa.Column('AgeYear', sa.Integer(), nullable=True),
    sa.Column('GenderID', sa.Integer(), nullable=True),
    sa.Column('VictimPolice', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['casemaster.CaseMasterID'], ),
    sa.PrimaryKeyConstraint('VictimMasterID')
    )
    op.create_table('arrestsurrender',
    sa.Column('ArrestSurrenderID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=True),
    sa.Column('ArrestSurrenderTypeID', sa.Integer(), nullable=True),
    sa.Column('ArrestSurrenderDate', sa.Date(), nullable=True),
    sa.Column('ArrestSurrenderStateId', sa.Integer(), nullable=True),
    sa.Column('ArrestSurrenderDistrictId', sa.Integer(), nullable=True),
    sa.Column('PoliceStationID', sa.Integer(), nullable=True),
    sa.Column('IOID', sa.Integer(), nullable=True),
    sa.Column('CourtID', sa.Integer(), nullable=True),
    sa.Column('AccusedMasterID', sa.Integer(), nullable=True),
    sa.Column('IsAccused', sa.Boolean(), nullable=True),
    sa.Column('IsComplainantAccused', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['AccusedMasterID'], ['accused.AccusedMasterID'], ),
    sa.ForeignKeyConstraint(['ArrestSurrenderDistrictId'], ['district.DistrictID'], ),
    sa.ForeignKeyConstraint(['ArrestSurrenderStateId'], ['state.StateID'], ),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['casemaster.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['CourtID'], ['court.CourtID'], ),
    sa.ForeignKeyConstraint(['IOID'], ['employee.EmployeeID'], ),
    sa.ForeignKeyConstraint(['PoliceStationID'], ['unit.UnitID'], ),
    sa.PrimaryKeyConstraint('ArrestSurrenderID')
    )
    op.create_table('inv_arrestsurrenderaccused',
    sa.Column('ArrestSurrenderID', sa.Integer(), nullable=False),
    sa.Column('AccusedMasterID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AccusedMasterID'], ['accused.AccusedMasterID'], ),
    sa.ForeignKeyConstraint(['ArrestSurrenderID'], ['arrestsurrender.ArrestSurrenderID'], ),
    sa.PrimaryKeyConstraint('ArrestSurrenderID', 'AccusedMasterID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inv_arrestsurrenderaccused')
    op.drop_table('arrestsurrender')
    op.drop_table('victim')
    op.drop_table('complainantdetails')
    op.drop_table('chargesheetdetails')
    op.drop_table('actsectionassociation')
    op.drop_table('accused')
    op.drop_table('casemaster')
    op.drop_table('employee')
    op.drop_table('unit')
    op.drop_table('crimeheadactsection')
    op.drop_table('court')
    op.drop_table('section')
    op.drop_table('district')
    op.drop_table('crimesubhead')
    op.drop_table('unittype')
    op.drop_table('state')
    op.drop_table('religionmaster')
    op.drop_table('rank')
    op.drop_table('occupationmaster')
    op.drop_table('gravityoffence')
    op.drop_table('designation')
    op.drop_table('crimehead')
    op.drop_table('castemaster')
    op.drop_table('casestatusmaster')
    op.drop_table('casecategory')
    op.drop_table('act')
    # ### end Alembic commands ###
